### ISSUE TITLE
video is displayed at the top left of the window

### ISSUE THREAD

**Issue by sinmsinm** [loowid/loowid#104]
@SedueRey  could it be possible to put in the center? If not we could think about resizing the window to fit it with the correct size.

**Comment by SedueRey** [comment]
I'm going to take a look to it right now

**Comment by SedueRey** [comment]
I've trying in local in firefox and chrome and video fits in center of the framewindow. Could you upload a capture? (This is Win7 64bits, maybe is only in linux, I can run my VirtualBox)

![capture_video](https://cloud.githubusercontent.com/assets/3238226/6201292/967145d6-b4a0-11e4-80b7-1705ffdff5de.jpg)

**Comment by sinmsinm** [comment]
I think that it's produced with small video's . Maybe should be better resize the widow once video is opened?

![left-video-chrome](https://cloud.githubusercontent.com/assets/1745437/6202939/caeb18f4-b505-11e4-97ef-1e092e2a3de1.png)

**Comment by SedueRey** [comment]
mmmm... yes. If video is smaller than window we should resize the window frame. I've put a max-width:100% and width:100% but if it's smaller it would be like your webcam does

**Comment by sinmsinm** [comment]
Ok. I'll do it.

El Dg, 15 Feb., 2015 18.42 Eduardo Rey Jara <notifications@github.com> va
escriure:
