### ISSUE TITLE
Record streams and upload to storage location.

### ISSUE THREAD

**Issue by sinmsinm** [loowid/loowid#14]
Sessions won't be recorded on servers, but it would be interesting to allow participants to record the streams they are receiving and upload them to a location (drive, dropbox, local file system...)

**Comment by Yaco** [comment]
This would be really great!

**Comment by sinmsinm** [comment]
Thanks, at the moment the development of this feature is frozen. But it's on the top of our "wish list". We would be glad to receive any help to design or develop it.
