### ISSUE TITLE
Add title to room's elements

### ISSUE THREAD

**Issue by sinmsinm** [loowid/loowid#147]
In order to improve accessibility and ux some titles with extended descrition must be adden in the room:
* Start/stop media buttons
* Window buttons
* Avatar
* buttons under each user in lisToggle/Expand pannels
* Add this buttons???
* Openable items in chat and urls
* Leave room
* Options???
* Audio alerts???

**Comment by macbroadcast** [comment]
#audioalerts and #emoji support is an important feature IMHO what about male/female icons ? :+1:

**Comment by sinmsinm** [comment]
@macbroadcast  a female icon was adden in other issue :)
