### ISSUE TITLE
How does Loowid work in multi party conf?

### ISSUE THREAD

**Issue by hdavy2002** [loowid/loowid#173]
HI there,

I like what I see. I was trying to find out what kind of architecture is Loowid. I mean, Mess, Routing or MCU. I am looking at multi party conf. Would that mean, the sender has to send multiple streams in different directions and receive the same or Loowid would mix all the streams and then just send one stream in all directions.

Any possibilities to use an MCU like Jitsi VideoBridge? So far what I have understood that is peer to peer. I was worried about bandwidth of a peer, if he is using his cell phone to connect for a conf. If he has to send multiple streams and receive multiple streams then it will an awful experience for him. One to one is great. Please could you give insight on multi conf. Many thanks in advance.

Cheers

**Comment by sinmsinm** [comment]
Hi, Loowid streams each media to every connected users. So if there is a room with 10 people and you start sharing your media you'll be sending the stream to the 9 others. Nowadays there is no intention to implement an MCU. We focus on smalls rooms for now but all help is welcome to go one step forward.

**Comment by hdavy2002** [comment]
Thanks for your reply. I understand it better now.
