### ISSUE TITLE
Improve UI when you have more than 8-10 users connected

### ISSUE THREAD

**Issue by jmarianolujan** [loowid/loowid#179]
When you have more than 8-10 users connected, you can't see all of them unless you scroll down the list. A simple improvement could be to minimize or reorder the information shown for each user when you have that many connections. The current UI is great for users up to 5-6. Great work!

![captura_de_pantalla_111215_124152_pm](https://cloud.githubusercontent.com/assets/11275984/11117522/c5f4bcec-893a-11e5-8c21-d9b8ef03ec5a.jpg)

**Comment by SedueRey** [comment]
I will do it, you are absolutely right :)

**Comment by juanjmerono** [comment]
I'm thinking in reduce the size of avatars, using ellipsis in names and also remove the redundant "viewer" string.
