### ISSUE TITLE
Unable to run it following the instructions

### ISSUE THREAD

**Issue by Yaco** [loowid/loowid#195]
Hi folks,
I am trying to run it following the instructions. I tryed it all the posibilites (with and without grunt, also using docket). This is my output trying with ```grunt```:

```
[yaco@manjaro loowid]$ grunt cluster --sport=9090 --port=8080 --bport=7000 --nodes=3  
Running "jshint:all" (jshint) task
>> 58 files lint free.

Running "uglify:build" (uglify) task
>> 1 sourcemap created.
>> 1 file created.

Running "less:prod" (less) task
File public/css/loowid.min.css created: 179.29 kB → 153.69 kB

Running "concurrent:cluster" (concurrent) task
Running "watch" task
Waiting...
Running "shell:mongo" (shell) task
Running "nodemon:proxy" (nodemon) task
Running "nodemon:dev0" (nodemon) task
Running "nodemon:dev1" (nodemon) task
Running "nodemon:dev2" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: log.js proxy.js server.js webrtc.io.js /home/yaco/Programacion/GitHub/loowid/app/**/*
[nodemon] starting `node proxy.js 3`
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: log.js proxy.js server.js webrtc.io.js /home/yaco/Programacion/GitHub/loowid/app/**/*
[nodemon] starting `node server.js 7001`
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: log.js proxy.js server.js webrtc.io.js /home/yaco/Programacion/GitHub/loowid/app/**/*
[nodemon] starting `node server.js 7002`
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: log.js proxy.js server.js webrtc.io.js /home/yaco/Programacion/GitHub/loowid/app/**/*
[nodemon] starting `node server.js 7003`
[nodemon] clean exit - waiting for changes before restart
```
When I try to load the app using my browser I alway get ```ERR_CONNECTION_REFUSED```. I tried different ports, with the same result. What I am missing? I ran out of ideas. 

Thanks in advance!

**Comment by juanjmerono** [comment]
I've tried your command and it works as expected. With the parameter that you are using you must type **https://localhost:9090/** in your browser to connect. Anyway you can just type *grunt* or *sudo grunt* to use default https port and connect with **https://localhost/**

If you are looking for a fast test try with
```docker run -d -p 443:443 loowid/loowid```

After that you can browse to **https://docker-machine-ip/** and you don't need to install, mongo, nodejs or any other stuff.

**Comment by Yaco** [comment]
I didn't set SSL certificates, so I am trying to connect using http and not https. Using the mentioned parameters I am trying to connect to **http://localhost:8080/**. Accoring to the documentation, "If no certificate available LooWID startup in http port". 

I just tryed the same command without defining ```sport```: ```grunt cluster --port=8080 --bport=7000 --nodes=3  ```

I get the same error... What else can I try? Is there any log I can check?

**Comment by Yaco** [comment]
Ok, I am able to access to the site with http://localhost:7001/ but not in 8080. So the app is working, but not in the standards ports. I tried the following command with the same situation:

```grunt --port=80 --sport=443 --bport=8000``` 

In that case, I am able to load in in port 8001 or 8002.

Any clue?

**Comment by Yaco** [comment]
Thanks Juan, but the commit didn't fix this issue for me. I get the same error. Can you re-open the issue?

**Comment by juanjmerono** [comment]
Really? Did you try with http://localhost:9090/ ??

**Comment by Yaco** [comment]
Just tryed it again and it works as you said. I was trying to connect to --port and not --sport.

Thanks!
