### ISSUE TITLE
localStorage exceeds the quota when there are some recordings

### ISSUE THREAD

**Issue by sinmsinm** [loowid/loowid#226]
I got a quota exceeding exception when I tried to record a session. Could it be that there were some recordings and the thumbnail images were stored as text in the localStorage?

```
angular.min.js:84 Error: Failed to set the ‘loowidRecordings’ property on ‘Storage’: Setting the value of ‘loowidRecordings’ exceeded the quota.
   at Object.fn (mediaservice.js:431)
   at h.$digest (angular.min.js:99)
   at h.$apply (angular.min.js:102)
   at Object._this._data.safeApply (uihandler.js:13)
   at records.js:193
```

**Comment by SedueRey** [comment]
Maybe could be used IndexedDB to store thumbnail images? With something like https://github.com/jakearchibald/idb to avoid using ugly IndexedDB as it

**Comment by juanjmerono** [comment]
The bug is due to the new use of FileSystem API, so I guess we could use some file to store this info and avoid the local storage limit.

**Comment by SedueRey** [comment]
I didn't knew that. Thanks
