### ISSUE TITLE
No issues , just a question ;)

### ISSUE THREAD

**Issue by macbroadcast** [loowid/loowid#30]
Hello, first of all , this is one of the best #WebRTC frameworks i found since months, it´s not just working seamlessly and looks awsome ,it has localization capabilities and thats a feature i missed on anything i saw in the past.  I would like to use loowid on my main page, but would like to embed a  boootstrap navigation on top ( where i like to place the link back to you , to my blog and some examples i am working on) , but looking at the files , i have no idea in whitch file i need to place it.
Thanks a lot

P.S. I am translating the Resource.bundle.json to german right now ;)

**Comment by sinmsinm** [comment]
Hi, good to know that LooWID is useful for you. Jade is the framework that renders html and sends it to the browser. By default, in the footer layer it adds just the loowid.min.js and the loowid.min.css If you need to add more libraries, do it to client/js  and annouce them adding the references to gruntfile.js to be included and mapped to the loowid.min.js.  The same for css in client/less
I think that there is an angular-ui bootstrap library already included but not the css (I should see if we still are using them).

Then depending what you you want to use it would be necessary to inject the dependencies to angular modules (client/js/app.js)

I hope it make sense :-)

It will be great to have German in LooWID :+1:  Thanks a lot.

**Comment by macbroadcast** [comment]
Thanks for your reply @sinmsinm , i understand  not anything but its allright, i am in the progress of learning  :bowtie:

P.S. The german translation is ready :relieved: , it will be reviewed from a friend and i will send it later via email. How you detect the language ? browser / system settings or ip ?

**Comment by juanjmerono** [comment]
You can create a fork in github and submit a pull request if you want. This is the proper way to contribute and be recognized as contributor, anyway send us an email if you feel more comfortable with that, thank you so much for your contribution !! :clap: :clap: :+1:

**Comment by sinmsinm** [comment]
@macbroadcast , this is a great new. I'm sure that german will look pretty well.  The language is determined by browser preferences, so if you have german as your default language loowid will render german messages. 

It's a pity that my explanation doesn't help

**Comment by macbroadcast** [comment]
Thanks @sinmsinm German is a bit difficult you can have a more serious and the personal salutation , because we germans normaly don´t say "you" to everyone, thats a bit missleading to most foreign people, but after i wrote half of  the "serious way", i felt a bit unhappy and i changed it to the more personel salutation. I think i will try it like @juanjmerono recommended, i need to learn it anyway. :stuck_out_tongue_closed_eyes:
