### ISSUE TITLE
The slogan text is not i18n

### ISSUE THREAD

**Issue by sinmsinm** [loowid/loowid#45]
The slogan text LooK What I'm Doing in the main page should be i18n.

**Comment by juanjmerono** [comment]
Why? I think this slogan shouldn't be translated. Maybe changed by "LOOWID"?

**Comment by sinmsinm** [comment]
I agree with we should maintain it untranslated, but sounds reasonable to have the text under an i18n key. It could help people to customize their own forks. I personally would maintain the long version "Look What I'm doing"  to help users to understand where the term of LooWID comes from. What do you think?

**Comment by juanjmerono** [comment]
Done !

**Comment by macbroadcast** [comment]
i did not ment to raise an issue, i just thought i made a mistake, its all good ;)
