### ISSUE TITLE
App does not work with startssl certificate

### ISSUE THREAD

**Issue by macbroadcast** [loowid/loowid#46]
I just figured that  my current example page at http://www.stattfernsehen.com/  returns an "page does not exist", work fine without the "www".

**Comment by sinmsinm** [comment]
Hi, I tried and I got DNS error in the browser. Did you, or your hosting
provider, change anything that can affect? If not , are you seeing anything
in the log that could help to understand what is happening?

Alex.

2015-01-10 17:24 GMT+01:00 macbroadcast <notifications@github.com>:

**Comment by macbroadcast** [comment]
I am using digital ocean and cloudflare and i changed the settings , see what happens in a few hours when the DNS is redistributed ;)

**Comment by macbroadcast** [comment]
Now i created a endless loop "Fehlercode: ERR_TOO_MANY_REDIRECTS"

**Comment by sinmsinm** [comment]
Hi, it's strange. We had the app in openshift responding directly to the domain www.loowid.com 
Our DNS in spain handles loowid.com requests and the webserver redirects to www.loowid.com

Maybe @juanjmerono have any idea to try!

**Comment by juanjmerono** [comment]
What message did you see when your server starts? "[INFO] server - Running development environment !!" or "[INFO] server - Running production environment !!"?

The app only redirects from http to https, but your domain is redirecting from https to http also, I don't know why. In openshift (production environment) the app is listening in http port (and openshift do the balance in https calling nodejs server listen in the http internal port), but in development environment is listening in two different ports https and http (to do the redirect and let the user go to the right place whatever he types).

Probably you are running in development mode (because openshift is not detected), so both ports are listening, but your cloud probably is only handling http and redirects from https to http and the app from http to https in an infinite loop.

Sounds reasonable?

**Comment by macbroadcast** [comment]
Thanks makes sense, you guys allways mention openshift, i am not using openshift and yes it runs in development enviroment. 
`[2015-01-14 08:51:53.490] [INFO] server - Running development environment !!
`how can i start server in production mode ?
I changed the DNS server back to digital ocean and it works with "www" and without, but my goal is to run it with cloudflare DNS and protection.

My other and most importand problem is i cant get LooWID to work with an Startssl certificate.
I created the CRT request, tried both with the startssl wizzard and on server, renamed it private.pem
then i put the data in the wizzard and created the  certificate and renamed it public.pem
Server starts ,but website is not available, no error message nothing...

thanks

**Comment by juanjmerono** [comment]
The difference between development and production (openshift for us) is only that in development start listening ports in http and https, but in production mode only http (it expected that the load balancer holds https), so there is no problem if you need to run both ports in your production environment (because your hosting is not adding any balancer like usually happens at localhost). 

The problem with the certificate is that the browser is not able to resolve the whole path to the root CA, so you could add in the public key file the StartSSL CA.

**Comment by macbroadcast** [comment]
I know @juanjmerono you told me allready  but what does that mean :
"so you could add in the public key file the StartSSL CA."
And how do i start the server in production mode ? I think not many people using openshift so its necessary to explain how it works in a standart enviroment, or you using the openshift certificate ?

**Comment by juanjmerono** [comment]
Yes you could append CA in public key file, and you don't need to start the server in production mode if you need to listen at http and https ports, so development is right for you.

**Comment by macbroadcast** [comment]
:+1:  Will try tomorrow and report my success  :stuck_out_tongue:

**Comment by macbroadcast** [comment]
Using this manual https://www.startssl.com/?app=42 tryed 3 times allways the same result  :rage:

http://pastebin.com/N7PF5XkF

**Comment by juanjmerono** [comment]
Ok, finally I think I found your problem...
We only handle cert and key options in our credentials object, but there is another property named "ca" that is an array to hold the complete chain... so, please create your ca.pem file with this command:

cat ca.pem sub.class1.server.ca.pem > loowid/ca.pem

and apply this patch:

diff --git a/server.js b/server.js
index b30d4cf..68ed2f3 100644
--- a/server.js
+++ b/server.js
@@ -42,9 +42,11 @@
 	// Generado con http://www.cert-depot.com/
 	var privateKey = fs.readFileSync(process.env.PRIVATE_KEY || 'private.pem');
 	var certificate = fs.readFileSync(process.env.PUBLIC_KEY || 'public.pem');
+	var certificateAuth = fs.readFileSync('ca.pem');
 	var credentials = {
 		key : privateKey,
-		cert : certificate
+		cert : certificate,
+		ca: certificateAuth
 	};
 	sserver = require('https').createServer(credentials, app);
 }

**Comment by juanjmerono** [comment]
```
diff --git a/server.js b/server.js
index b30d4cf..68ed2f3 100644
--- a/server.js
+++ b/server.js
@@ -42,9 +42,11 @@
 	// Generado con http://www.cert-depot.com/
 	var privateKey = fs.readFileSync(process.env.PRIVATE_KEY || 'private.pem');
 	var certificate = fs.readFileSync(process.env.PUBLIC_KEY || 'public.pem');
+	var certificateAuth = fs.readFileSync('ca.pem');
 	var credentials = {
 		key : privateKey,
-		cert : certificate
+		cert : certificate,
+		ca: certificateAuth
 	};
 	sserver = require('https').createServer(credentials, app);
 }
```

**Comment by macbroadcast** [comment]
Thanks so much @juanjmerono  :+1:  sorry for my last stupid question,  we have 3 files now, where do i create  the public.pem from ? :blush:

1. ´openssl rsa -in ssl.key -out loowid/ssl.key´ will be renamed to private.pem
2. ´cat ca.pem sub.class1.server.ca.pem > loowid/ca.pem´  stay like it is
3. public.pem ?

**Comment by juanjmerono** [comment]
I think ssl.crt is your public.pem file.

**Comment by macbroadcast** [comment]
Thanks for your patience, applied changes in server.js , server starts without errors , but no website and still same error

`ERR_CONNECTION_CLOSED`

Lets contignue tomorrow, i could give you acess to the server if you want. :-)

**Comment by juanjmerono** [comment]
I've seen this error: ERR_CERT_AUTHORITY_INVALID
You could try to add the files in array format instead of concat them in one file.
var certificateAuth = fs.readFileSync('ca.pem');
var certificateAuth2 = fs.readFileSync('sub.ca.pem');
...
ca: [ certificateAuth2, certificateAuth ]

**Comment by macbroadcast** [comment]
Looking at this startssl  how-to @juanjmerono  i need to contradict 
https://www.startssl.com/?app=42

ssl.key is my private key  and i generate my certificate out of:
cat ssl.crt < my cert - sub.class1.server.ca.pem < intermediate cert - ca.pem < root cert > loowid/ssl-unified.crt
so ssl key is my private.pem and ssl-unified.crt is my public.pem, so we are still here.

´crypto.js:135
  if (options.cert) c.context.setCert(options.cert);
                              ^
Error: error:0906D066:PEM routines:PEM_read_bio:bad end line
    at Object.exports.createCredentials (crypto.js:135:31)
    at Server (tls.js:1128:28)
    at new Server (https.js:35:14)
    at Object.exports.createServer (https.js:54:10)
    at Object.<anonymous> (/root/loowid/server.js:51:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[nodemon] app crashed - waiting for file changes before starting...´

**Comment by juanjmerono** [comment]
I've tested locally doing this:

cat ca.pem sub.class1.server.ca.pem ssl.ctr > loowid/public.pem
cp ssl.key > loowid/private.pem

My private key is encrypted, so node ask for a password during starting process, but after you enter the password everything works as expected, even without using the patch that I wrote.

I don't know what's wrong with your configuration.

**Comment by macbroadcast** [comment]
thanks @juanjmerono , I see you changed the order ? :wink: 

cat ssl.crt sub.class1.server.ca.pem ca.pem > loowid/public.pem <i am using this from the startssl page
cat ca.pem sub.class1.server.ca.pem ssl.ctr > loowid/public.pem < you were using this

I will try right now ,if it doesnt work i will reinstall !

**Comment by juanjmerono** [comment]
@macbroadcast please let us know if you still having problems

**Comment by macbroadcast** [comment]
Why you closed the issue ?

**Comment by juanjmerono** [comment]
:sweat_smile: Sorry, I was looking for some feedback about this. I guess now the new #85 issue could help to solve this issue isn't it?
