### ISSUE TITLE
No accept button on mobile

### ISSUE THREAD

**Issue by macbroadcast** [loowid/loowid#47]
![img_2792](https://cloud.githubusercontent.com/assets/7961/5692745/9685092c-9902-11e4-8ab5-537323d487e9.PNG)

**Comment by sinmsinm** [comment]
What browser and  SO are you using? That message seems to be an alert about your browser is not compatible. Chrome for IOs doesn't run WebRTC at the moment.

**Comment by macbroadcast** [comment]
It was an iphone 6 with the lastest OS and chrome, i wasnt aware that chrome on IOS dont support WebRTC

**Comment by sinmsinm** [comment]
Yes, it's a pitty. I hope that Apple - Chrome could resolve soon.

2015-01-10 22:42 GMT+01:00 macbroadcast <notifications@github.com>:
