### ISSUE TITLE
Take some variable config from file

### ISSUE THREAD

**Issue by SedueRey** [loowid/loowid#52]
This setup would allow us to have different configuration files per project and different installation in the same machine.

This file maybe could be read from command line or similar

**Comment by juanjmerono** [comment]
Now with --port --sport and --bport you are able to set the ports you want to use for listen and avoid collisions with other apps.

**Comment by sinmsinm** [comment]
Mola el concepto, pero debemos ocultar la URL para que no se vea. En todo
caso la podríamos quitar solo si está compartiendo el escritorio. Que te
parece?


2015-01-27 16:40 GMT+01:00 Juanjo Meroño <notifications@github.com>:

**Comment by SedueRey** [comment]
Ahora mismo se supone que es sólo con el escritorio pero seguro que me he
comido un flag o algo XDD
